# fly.toml app configuration file generated for cryptobot on 2023-06-03T16:54:24-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cryptobot"
primary_region = "gdl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
